version: '2'
services:
    jhipstermonolithicapp-app:
        image: jhipstermonolithicapp
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://jhipstermonolithicapp-mysql:3306/jhipstermonolithicapp?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=jhipstermonolithicapp-elasticsearch:9300
        ports:
            - 8080:8080
    jhipstermonolithicapp-mysql:
        extends:
            file: mysql.yml
            service: jhipstermonolithicapp-mysql
    jhipstermonolithicapp-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: jhipstermonolithicapp-elasticsearch
